# Generated by Django 5.1.5 on 2025-02-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default={'title': 'ádasd'}, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.CharField(max_length=1000),
        ),
    ]
